server:
  port: 80

build:
  name: @project.name@
  version: @project.version@
spring:
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
